import React from "react";

export const Context = React.createContext({
  username: {},
  firstName: {},
  lastName: {},
  nickName: {},
  username: {},
  email: {},
  password: {},
  confirmPassword: {},
  phone: {},
  promotional: {},
  referred: {},
  checkbox: {},
  captcha: {},
  captchaInput: {},
  redirect: {},
  loading: {},
  handleChangeLogin: () => {},
  handleSubmitLogin: () => {},
  goAccount: () => {},
  resetInputs: () => {},
  handleChangeSignup: () => {},
  handleSubmitSignup: () => {},
  postData: () => {},
  validateForm: () => {},
  handleChangeBox: () => {},
  randomPassword: () => {},
  randomCode: () => {},
  handleVisiblePassword: () => {},
});
