import React from "react";

export const Context = React.createContext({
  errors: {
    firstName: "",
    lastName: "",
    nickName: "",
    username: "",
    email: "",
    password: "",
    confirmPassword: "",
    phone: "",
    promotional: "",
    // generate: "",
    referred: "",
    captchaInput: "",
  },
  username: "",
  password: "",
  firstName: "",
  lastName: "",
  nickName: "",
  username: "",
  email: "",
  confirmPassword: "",
  phone: "",
  promotional: "",
  referred: "",
  // generate: "",
  checkbox: "",
  captcha: "",
  captchaInput: "",
  redirect: "",
  loading:"",
  // type: "",
  handleChangeLogin: () => {},
  handleSubmitLogin: () => {},
  goAccount: () => {},
  handleSubmitSignup: () => {},
  handleChange: () => {},
  postData: () => {},
  validateForm: () => {},
  randomPassword: () => {},
  handleChangeBox: () => {},
  randomCode: () => {},
  // resetInputs: () => {},
  // handleVisiblePassword: () => {},
});
